### PR TITLE
Fix SSL Handshake with Binance Testnet

### PR DESCRIPTION
**Pull request by noobaldrin**

### CODE REVIEW

**Comment by niXman** [comment]
hi,

has this been tested on a regular binance connection?

**Comment by noobaldrin** [comment]
> hi,
> 
> has this been tested on a regular binance connection?

Hello,

Yes it works on both Binance live api and Testnet. I've tested it on your main.cpp.

The issue was that Testnet doesn't have a specific port for its websocket connection (both api and websocket are in port 443) so it keeps returning the api's SSL instead of the SSL for websocket everytime the client access port 443.

This is the original code snippet from Boost Beast's websocket example.
```
// Set SNI Hostname (many hosts need this to handshake successfully)
        if(! SSL_set_tlsext_host_name(
                ws_.next_layer().native_handle(),
                host_.c_str()))
        {
            ec = beast::error_code(static_cast<int>(::ERR_get_error()),
                net::error::get_ssl_category());
            return fail(ec, "connect");
        }
```

**Comment by noobaldrin** [comment]
Correction:
*Both api and websocket are in testnet.binance.vision:443 

Now that I read the comment again in Beast's example, maybe the server can't differentiate between accessing "/" and "/ws" without SNI using the same SSL/TLS.

**Comment by niXman** [comment]
thank you!

**Pull request merged**
